### ISSUE TITLE
Enable auto off for switch

### ISSUE THREAD

**Issue by PieterDes** [phenotypic/homebridge-nodemcu-relay#1]
Hi,

this might be a stupid question but is there a way to put the switch back to off automatically after you switched it on ?

I am now using it to open my gate with the momentary switch and it works great. Only issue is that the switch for my gate stays on when it is opened, and when I close it it is off again.

I would like it to return to off automatically anytime I switch it on. Like a push button.

This option "enableAutoOff" exists for other homebridge plugins, just wondering how it could be done here.

Thanks !

**Comment by phenotypic** [comment]
Hi there,

If I understand your issue correctly, there is no issue with the controlling of the actual gate itself - rather, you'd like the virtual switch within the app to return to OFF after activating the gate in either direction.

Unfortunately, this repository is not a plugin - the README advises you to use [homebridge-http](https://github.com/rudders/homebridge-http), so there is no way for me to integrate this functionality. 

However, I'm still not quite clear on why you'd like this behaviour. Surely you'd want the gate to appear ON when it's open and OFF when it's closed as an indication of its true state?

**Comment by PieterDes** [comment]
Hi,
There is indeed no issue with controlling the actual gate itself. 
But as there are other ways of opening and closing it (other remotes)I do not know if it is open or closed. So I can not know if I need to say “Siri turn gate on” or “Siri turn gate off” to open the gate. 
If the switch would always be on off after an action (opening or closing) then I can always say “Siri turn gate on” and it will always close or open and not depend on the state the switch was in. 

Hope this is more clear 😀
Another issue I get is that the Apple Watch tells me it got no response from the gate, but it does open. Weird.

**Comment by phenotypic** [comment]
Unfortunately, as I said, this repository is not a plugin so you'd have to request this functionality from whichever plugin you are using e.g. [homebridge-http](https://github.com/rudders/homebridge-http).

But, if you have some way of detecting the true state of the gate from the NodeMCU, I'd recommend my plugin [homebridge-web-lock](https://github.com/Tommrodrigues/homebridge-web-lock), as it will relay the true state of the gate back to the app regardless of which method you have used to control it.

Best, Tom
