### ISSUE TITLE
2 relays

### ISSUE THREAD

**Issue by Meijti** [phenotypic/homebridge-nodemcu-relay#3]
Dear Tom,

I am trying my very best to add control for a second relay but I am unable to do it. Can you help me? I have very little experience.
Just need to add a second pin..

Best regards,
Tim

**Comment by phenotypic** [comment]
Hi there, this is fairly easy to accomplish. You just need to add another line every time the `digitalWrite()` function is called.

At the top of the script, below `const int relayPin = 13;`, add new line `const int relayPin2 = #;` where `#` is the number of the extra pin you want to add.

Then, every time the script calls `digitalWrite(relayPin, STATE);`, add a new line directly below `digitalWrite(relayPin2, STATE);` where `STATE` is is either `relayOff` or `relayOn` depending on the previous line`

For example, below line `99`, you would write `digitalWrite(relayPin2, relayOn);`

This will mirror the state of the first relay to the second relay every time it is called.

**Comment by Meijti** [comment]
Thanks for the quick response! got it kindoff working. I want to control them seperately though..

how does the /status work for a second relay?

**Comment by phenotypic** [comment]
To get the relays working separately the script would require some more significant modifications to retain functionality for the three activation types. Unfortunately, I don't have the time or incentive to implement those changes myself. You are more than welcome to fork the project and attempt this yourself though!

To get the `/status` for both relays you would need to modify the function on line `20` accordingly.
